name: RSS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Pandoc
        run:
          sudo apt-get install -y pandoc

      - name: Build RSS
        run:
          ./rss.sh
        working-directory: docs/

      - name: Commit Updated
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build feed.xml
