name: RSS

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/feed.xml'
      - 'docs/sitemap.xml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install Pandoc
        run:
          sudo apt-get install -y pandoc

      - name: Build RSS
        run: |
          git -C ${{ github.workspace }} pull --rebase
          ./rss.sh
        working-directory: docs/

      - name: Commit Updated
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Build feed.xml
